from __future__ import annotations

from aod._internal.application.logger.logger import Logger


class NullLogger(Logger):
    def debug(self, msg: str, **context: object) -> None: ...
    def info(self, msg: str, **context: object) -> None: ...
    def warning(self, msg: str, **context: object) -> None: ...
    def error(self, msg: str, **context: object) -> None: ...
