from aod._internal.core.domain_exception import (
    ClassExpectedError,
    DuplicateDomainTypeError,
    HandlerEntityMismatchError,
    HandlerTypeMismatchError,
    InvalidCommandFieldTypeError,
    InvalidEntityTypeError,
    InvalidGenericTypeArgError,
    InvalidNestedTypeError,
    InvalidProjectionTypeError,
    InvalidQueryResultTypeError,
    InvalidRootEntityTypeError,
    InvalidServiceParameterError,
    InvalidServiceTypeError,
    InvarianceException,
    MutationForbiddenException,
    UnresolvableHandlerTypeError,
)

__all__ = [
    "ClassExpectedError",
    "DuplicateDomainTypeError",
    "HandlerEntityMismatchError",
    "HandlerTypeMismatchError",
    "InvalidCommandFieldTypeError",
    "InvalidEntityTypeError",
    "InvalidGenericTypeArgError",
    "InvalidNestedTypeError",
    "InvalidProjectionTypeError",
    "InvalidQueryResultTypeError",
    "InvalidRootEntityTypeError",
    "InvalidServiceParameterError",
    "InvalidServiceTypeError",
    "InvarianceException",
    "MutationForbiddenException",
    "UnresolvableHandlerTypeError",
]
