from __future__ import annotations

from aod._internal.application.unit_of_work.unit_of_work import UnitOfWork


class NullUnitOfWork(UnitOfWork):
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def begin(self) -> None: ...
